import { parseEther } from "ethers";

export const TEST_CONFIG = {
    TARGET_AMOUNT_MIN_ETH: '10',
    TARGET_AMOUNT_MAX_ETH: '100',
    TARGET_AMOUNT_FRACTION_DIGITS: '2',
    TARGET_AMOUNT_STEP_ETH: '0,25',

    MIN_CONTRIBUTION_MAX_ETH: '0.1',
    MIN_CONTRIBUTION_MIN_ETH: '0.001',
    MIN_CONTRIBUTION_FRACTION_DIGITS: '5',
    MIN_CONTRIBUTION_STEP_ETH: '0.0001',

    MAX_CONTRIBUTION_MAX_ETH: '5',
    MAX_CONTRIBUTION_MIN_ETH: '1',
    MAX_CONTRIBUTION_FRACTION_DIGITS: '5',
    MAX_CONTRIBUTION_STEP_ETH: '0.1',


    END_TIMESTAMP_OFFSET_MIN_SECONDS: 3600,
    END_TIMESTAMP_OFFSET_MAX_SECONDS: 3600 * 24 * 7,

    NUM_INVESTORS: 5,

    IPFS_METADATA_HASH_BASE: 'QmTestHash',
    TOKEN_NAME_BASE: 'BlockSparkToken',
    TOKEN_SYMBOL_BASE: 'BST',

    TIME_TO_JUMP_AFTER_DEADLINE: 3600 * 24,

    SMALL_CONTRIBUTION_ETH: '0.1',
    LARGE_CONTRIBUTION_ETH: '2.0',
    CROSS_BOUNDARY_CONTRIBUTION_ETH: '3',
    
    FAILED_TO_ECTRACT_CAMPAIDN_ADRESS_ERROR: "Failed to extract campaign address",

    parseEth(amount: string){
        return parseEther(amount);
    },
};