/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as cаmpaignFactorySol from "./CаmpaignFactory.sol";
export * as mocks from "./mocks";
export { BlockSparkToken__factory } from "./BlockSparkToken__factory";
export { Campaign__factory } from "./Campaign__factory";
