/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICampaign,
  ICampaignInterface,
} from "../../../contracts/RejectETH.sol/ICampaign";

const _abi = [
  {
    inputs: [],
    name: "claimFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "invest",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICampaign__factory {
  static readonly abi = _abi;
  static createInterface(): ICampaignInterface {
    return new Interface(_abi) as ICampaignInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICampaign {
    return new Contract(address, _abi, runner) as unknown as ICampaign;
  }
}
