/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cаmpaignFactorySol from "./CаmpaignFactory.sol";
export type { cаmpaignFactorySol };
import type * as mocks from "./mocks";
export type { mocks };
export type { BlockSparkToken } from "./BlockSparkToken";
export type { Campaign } from "./Campaign";
