/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  RejectETH,
  RejectETHInterface,
} from "../../../../contracts/mocks/RejectETH.sol/RejectETH";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_campaign",
        type: "address",
      },
    ],
    name: "claimFundsFromCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_campaign",
        type: "address",
      },
    ],
    name: "investInCampaign",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_campaign",
        type: "address",
      },
    ],
    name: "refundFromCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061038e8061001f6000396000f3fe6080604052600436106100385760003560e01c8063a33d34a4146100b3578063ac3d15fb146100dc578063c9b5240e1461010557610078565b36610078576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161006f906102a8565b60405180910390fd5b6040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100aa906102a8565b60405180910390fd5b3480156100bf57600080fd5b506100da60048036038101906100d5919061032b565b610121565b005b3480156100e857600080fd5b5061010360048036038101906100fe919061032b565b610184565b005b61011f600480360381019061011a919061032b565b6101e7565b005b8073ffffffffffffffffffffffffffffffffffffffff1663ac3077736040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561016957600080fd5b505af115801561017d573d6000803e3d6000fd5b5050505050565b8073ffffffffffffffffffffffffffffffffffffffff1663590e1ae36040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156101cc57600080fd5b505af11580156101e0573d6000803e3d6000fd5b5050505050565b8073ffffffffffffffffffffffffffffffffffffffff1663e8b5e51f346040518263ffffffff1660e01b81526004016000604051808303818588803b15801561022f57600080fd5b505af1158015610243573d6000803e3d6000fd5b505050505050565b600082825260208201905092915050565b7f492072656a656374204554480000000000000000000000000000000000000000600082015250565b6000610292600c8361024b565b915061029d8261025c565b602082019050919050565b600060208201905081810360008301526102c181610285565b9050919050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006102f8826102cd565b9050919050565b610308816102ed565b811461031357600080fd5b50565b600081359050610325816102ff565b92915050565b600060208284031215610341576103406102c8565b5b600061034f84828501610316565b9150509291505056fea2646970667358221220a116222f425edc9cc2f823bd62744cd90d57acf67571fd1878a9f00ef95f704564736f6c634300081c0033";

type RejectETHConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RejectETHConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RejectETH__factory extends ContractFactory {
  constructor(...args: RejectETHConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RejectETH & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RejectETH__factory {
    return super.connect(runner) as RejectETH__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RejectETHInterface {
    return new Interface(_abi) as RejectETHInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): RejectETH {
    return new Contract(address, _abi, runner) as unknown as RejectETH;
  }
}
