/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RejectETHInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimFundsFromCampaign"
      | "investInCampaign"
      | "refundFromCampaign"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimFundsFromCampaign",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investInCampaign",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundFromCampaign",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimFundsFromCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investInCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundFromCampaign",
    data: BytesLike
  ): Result;
}

export interface RejectETH extends BaseContract {
  connect(runner?: ContractRunner | null): RejectETH;
  waitForDeployment(): Promise<this>;

  interface: RejectETHInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimFundsFromCampaign: TypedContractMethod<
    [_campaign: AddressLike],
    [void],
    "nonpayable"
  >;

  investInCampaign: TypedContractMethod<
    [_campaign: AddressLike],
    [void],
    "payable"
  >;

  refundFromCampaign: TypedContractMethod<
    [_campaign: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimFundsFromCampaign"
  ): TypedContractMethod<[_campaign: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "investInCampaign"
  ): TypedContractMethod<[_campaign: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "refundFromCampaign"
  ): TypedContractMethod<[_campaign: AddressLike], [void], "nonpayable">;

  filters: {};
}
