/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CampaignFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createCampaign" | "isCampaign"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CampaignCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isCampaign",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isCampaign", data: BytesLike): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignAddress: AddressLike,
    creator: AddressLike,
    ipfsHash: string,
    targetAmount: BigNumberish,
    endTimestamp: BigNumberish,
    tokenName: string,
    tokenSymbol: string
  ];
  export type OutputTuple = [
    campaignAddress: string,
    creator: string,
    ipfsHash: string,
    targetAmount: bigint,
    endTimestamp: bigint,
    tokenName: string,
    tokenSymbol: string
  ];
  export interface OutputObject {
    campaignAddress: string;
    creator: string;
    ipfsHash: string;
    targetAmount: bigint;
    endTimestamp: bigint;
    tokenName: string;
    tokenSymbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CampaignFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CampaignFactory;
  waitForDeployment(): Promise<this>;

  interface: CampaignFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createCampaign: TypedContractMethod<
    [
      _targetAmount: BigNumberish,
      _minContribution: BigNumberish,
      _maxContribution: BigNumberish,
      _endTimestamp: BigNumberish,
      _ipfsMetadataHash: string,
      _tokenName: string,
      _tokenSymbol: string
    ],
    [void],
    "nonpayable"
  >;

  isCampaign: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _targetAmount: BigNumberish,
      _minContribution: BigNumberish,
      _maxContribution: BigNumberish,
      _endTimestamp: BigNumberish,
      _ipfsMetadataHash: string,
      _tokenName: string,
      _tokenSymbol: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isCampaign"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(address,address,string,uint256,uint256,string,string)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
  };
}
